on:
  # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PULL_REQUEST: true
          REPOSITORIES: |
            particuleio/sync-test
          WORKFLOW_FILES: |
            .github
            .tools-version
            .releaserc
            .python-version
            .mergify.yml
            .gitignore
            .pre-commit-config.yaml
            .terraform-docs.yml

